#!/usr/bin/env python
"""Every figure in the paper, from one style, regenerated by one command.

Each figure reads the analysis JSON directly rather than taking numbers as arguments, so a rerun of
an experiment propagates into the figure without anyone retyping a value. Panels that show a
comparison draw the baseline in grey and the claim in colour, and any comparison that a bootstrap
called not-distinguishable is drawn with its interval crossing zero visible rather than as a bare
bar -- the figure should not imply a gap the statistics do not support.

  python paper/figures.py            # all figures that have their inputs
  python paper/figures.py f1 f5      # just these
"""
from __future__ import annotations
import json, sys
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

ANA = Path.home() / "zf_labelset/zf_detection_dataset_v1/analysis"
OUT = Path(__file__).resolve().parent / "figures"
OUT.mkdir(exist_ok=True)

# ---- one style, applied everywhere
INK, MUTE, GRID = "#1a1d21", "#8b9199", "#dfe3e8"
BLUE, ORANGE, GREEN, RED, PURPLE = "#2f6f9f", "#d1741f", "#3f8f6b", "#b5423a", "#6b5b95"
plt.rcParams.update({
    "figure.dpi": 130, "savefig.dpi": 200, "savefig.bbox": "tight",
    "font.family": "sans-serif",
    "font.sans-serif": ["Helvetica Neue", "Helvetica", "Arial", "DejaVu Sans"],
    "font.size": 9, "axes.titlesize": 10, "axes.labelsize": 9,
    "axes.edgecolor": MUTE, "axes.labelcolor": INK, "text.color": INK,
    "xtick.color": MUTE, "ytick.color": MUTE, "axes.spines.top": False,
    "axes.spines.right": False, "grid.color": GRID, "grid.linewidth": 0.6,
    "legend.frameon": False, "legend.fontsize": 8,
})


def load(name):
    p = ANA / name
    return json.loads(p.read_text()) if p.exists() else None


def finish(fig, name, note=None):
    if note:
        fig.text(0.005, -0.02, note, fontsize=7, color=MUTE, va="top")
    p = OUT / f"{name}.png"
    fig.savefig(p)
    plt.close(fig)
    print(f"  wrote {p.relative_to(Path(__file__).resolve().parent.parent)}")


def hbars(ax, labels, vals, colors, xlim, fmt="{:.3f}"):
    yy = np.arange(len(labels))[::-1]
    ax.barh(yy, vals, color=colors, height=0.62)
    for y, v in zip(yy, vals):
        ax.text(v + (xlim[1] - xlim[0]) * 0.012, y, fmt.format(v), va="center", fontsize=8,
                color=INK)
    ax.set_yticks(yy); ax.set_yticklabels(labels)
    ax.set_xlim(*xlim); ax.xaxis.grid(True); ax.set_axisbelow(True)


# ------------------------------------------------------------------ F1
def f1():
    """What pretraining buys, and what domain-specific pretraining does not."""
    ri, fb, av = load("randinit_control.json"), load("frame_baselines.json"), load("aves_baseline.json")
    if not (ri and fb):
        return print("  f1: needs randinit_control.json + frame_baselines.json")
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.4, 3.1),
                                 gridspec_kw=dict(width_ratios=[1, 1.05]))

    t = ri["layer_table"]
    labels = ["run11 (pretrained)", "weight-shuffled", "random init", "log-mel 384-d", "log-energy"]
    vals = [t["cnn"]["pretrained"], t["cnn"]["shuf_mean"], t["cnn"]["rand_mean"],
            ri["baselines"]["logmel"], ri["baselines"]["logenergy"]]
    hbars(a1, labels, vals, [BLUE, MUTE, MUTE, ORANGE, GRID], (0.45, 1.03))
    a1.axvline(ri["prevalence"], color=RED, lw=1, ls=":")
    a1.text(ri["prevalence"] + 0.005, -0.45, f"majority {ri['prevalence']:.3f}", color=RED,
            fontsize=7.5)
    a1.set_xlabel("AUC, 1 s windows, CNN output")
    a1.set_title("Pretraining is worth +0.244 at the CNN\nand the spectrogram is much closer than "
                 "random init", loc="left")

    rows = [("run11 L0", fb["full"]["hubert_L0"]["auc"], fb["full"]["hubert_L0"]["ap"], BLUE)]
    if av:
        b = av["best_aves"]
        rows.append((b["name"].replace("aves_", "AVES ").replace("_L", " L"), b["auc"], b["ap"], PURPLE))
    rows += [("log-mel 100 ms", fb["full"]["logmel_100ms"]["auc"], fb["full"]["logmel_100ms"]["ap"], ORANGE),
             ("log-mel 25 ms", fb["full"]["logmel_25ms"]["auc"], fb["full"]["logmel_25ms"]["ap"], ORANGE),
             ("log-energy", fb["full"]["logenergy"]["auc"], fb["full"]["logenergy"]["ap"], GRID)]
    yy = np.arange(len(rows))[::-1]
    a2.barh(yy + 0.16, [r[1] for r in rows], height=0.30, color=[r[3] for r in rows], label="AUC")
    a2.barh(yy - 0.16, [r[2] for r in rows], height=0.30, color=[r[3] for r in rows], alpha=0.45,
            label="AP")
    for y, r in zip(yy, rows):
        a2.text(r[1] + 0.008, y + 0.16, f"{r[1]:.3f}", va="center", fontsize=7.5)
        a2.text(r[2] + 0.008, y - 0.16, f"{r[2]:.3f}", va="center", fontsize=7.5, color=MUTE)
    a2.set_yticks(yy); a2.set_yticklabels([r[0] for r in rows])
    a2.set_xlim(0.2, 1.06); a2.xaxis.grid(True); a2.set_axisbelow(True)
    a2.set_xlabel(f"20 ms frames, n={fb['n_frames']:,}, prevalence {fb['prevalence']:.3f}")
    a2.set_title("At the native resolution the gap over mel is\n"
                 f"{fb['hubert_minus_mel100_auc']:+.3f} AUC but {fb['hubert_minus_mel100_ap']:+.3f} AP",
                 loc="left")
    a2.legend(loc="lower right")
    finish(fig, "f1_what_pretraining_buys",
           "Left: 1 s windows, majority rate 0.676. Right: 20 ms frames. AP is the honest metric at "
           "12% prevalence.")


# ------------------------------------------------------------------ F2
def f2():
    """Depth profile: the plateau, and that random init is flat."""
    ri = load("randinit_control.json")
    if not ri:
        return print("  f2: needs randinit_control.json")
    t = ri["layer_table"]
    keys = ["cnn"] + [f"L{i}" for i in range(12) if f"L{i}" in t]
    x = np.arange(len(keys))
    fig, ax = plt.subplots(figsize=(7.0, 3.2))
    ax.plot(x, [t[k]["pretrained"] for k in keys], "-o", color=BLUE, ms=4, label="run11 pretrained")
    for nm, c, ls in (("rand", MUTE, "-"), ("shuf", "#b0b6bd", "--")):
        m = np.array([t[k][f"{nm}_mean"] for k in keys])
        s = np.array([t[k][f"{nm}_sd"] for k in keys])
        ax.plot(x, m, ls, color=c, ms=3, marker="o",
                label="random init" if nm == "rand" else "weight-shuffled")
        ax.fill_between(x, m - s, m + s, color=c, alpha=0.18, lw=0)
    ax.axhline(ri["baselines"]["logmel"], color=ORANGE, lw=1.2, ls=":")
    ax.text(len(keys) - 0.4, ri["baselines"]["logmel"] + 0.006, "log-mel", color=ORANGE,
            fontsize=8, ha="right")
    ax.set_xticks(x); ax.set_xticklabels([k.upper() for k in keys], fontsize=8)
    ax.set_ylabel("AUC"); ax.set_xlabel("encoder depth")
    ax.yaxis.grid(True); ax.set_axisbelow(True)
    ax.set_title("Twelve transformer blocks add +0.011 over the CNN output;\n"
                 "the untrained network is flat, so depth is not the mechanism", loc="left")
    ax.legend(loc="center right")
    finish(fig, "f2_depth_profile",
           "Shaded band is ±1 sd over 3 random seeds / 2 shuffle seeds. Layers 0-8 are a plateau: "
           "per-layer winners are not resolvable.")


# ------------------------------------------------------------------ F3
def f3():
    """Temporal resolution: windowed vs continuous, and where context stops paying."""
    rs = load("resolution_sweep.json")
    if not rs:
        return print("  f3: needs resolution_sweep.json")
    ws = [1000, 500, 250, 125, 80, 40]
    w = [rs[f"w{k}"]["center"]["windowed_L0"] for k in ws]
    c = [rs[f"w{k}"]["center"]["continuous_L0"] for k in ws]
    m = [rs[f"w{k}"]["center"]["logmel"] for k in ws]
    fig, ax = plt.subplots(figsize=(7.0, 3.3))
    ax.plot(ws, w, "-o", color=BLUE, ms=5, label="windowed (encoder sees only the segment)")
    ax.plot(ws, c, "-s", color=GREEN, ms=5,
            label="continuous (full-recording context, pooled after)")
    ax.plot(ws, m, ":^", color=ORANGE, ms=4, label="log-mel")
    if "frames_20ms" in rs:
        ax.plot([20], [rs["frames_20ms"]["L0"]], "*", color=BLUE, ms=13)
        ax.annotate("20 ms frames", (20, rs["frames_20ms"]["L0"]), textcoords="offset points",
                    xytext=(6, -11), fontsize=7.5, color=BLUE)
    ax.axvline(125, color=MUTE, lw=1, ls="--")
    ax.annotate("crossover ~125 ms", (125, 0.70), textcoords="offset points", xytext=(7, 0),
                fontsize=8, color=MUTE)
    ax.set_xscale("log"); ax.set_xticks(ws + [20]); ax.set_xticklabels([str(k) for k in ws] + ["20"])
    ax.invert_xaxis()
    ax.set_xlabel("segment length (ms)"); ax.set_ylabel("AUC, centre label")
    ax.yaxis.grid(True); ax.set_axisbelow(True); ax.legend(loc="lower left")
    ax.set_title("Above 125 ms the encoder is better off seeing only the segment;\n"
                 "below it, full-recording context wins", loc="left")
    finish(fig, "f3_temporal_resolution",
           "Centre label (a window is positive if its midpoint is in a call) -- length-neutral, "
           "unlike overlap labelling which inflates long windows.")


# ------------------------------------------------------------------ F4
def f4():
    """Sub-frame onsets: interpolation is free and matches 4x the compute."""
    sf_ = load("subframe_onset.json")
    if not sf_:
        return print("  f4: needs subframe_onset.json")
    a = sf_["arms"]
    order = ["coarse_nearest", "coarse_interp", "shifted_K4_nearest", "shifted_K4_interp"]
    nice = {"coarse_nearest": "nearest frame\n(1x compute)", "coarse_interp": "interpolated crossing\n(1x compute)",
            "shifted_K4_nearest": "4 shifted passes,\nnearest", "shifted_K4_interp": "4 shifted passes,\ninterpolated"}
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.0, 3.1), gridspec_kw=dict(width_ratios=[1, 1]))
    x = np.arange(len(order))
    cols = [MUTE, BLUE, "#9aa2ab", "#6f9dc2"]
    a1.bar(x, [a[k]["med_abs_err_ms"] for k in order], color=cols, width=0.6)
    for i, k in enumerate(order):
        a1.text(i, a[k]["med_abs_err_ms"] + 0.25, f"{a[k]['med_abs_err_ms']:.1f}", ha="center",
                fontsize=8)
    a1.set_xticks(x); a1.set_xticklabels([nice[k] for k in order], fontsize=7.5)
    a1.set_ylabel("median |onset error| (ms)"); a1.yaxis.grid(True); a1.set_axisbelow(True)
    a1.set_title("Interpolating the threshold crossing costs nothing\nand matches 4x encoder compute",
                 loc="left")

    a2.bar(x, [a[k]["bias_ms"] for k in order], color=cols, width=0.6)
    a2.axhline(0, color=INK, lw=0.8)
    a2.axhline(10, color=RED, lw=1, ls=":")
    a2.text(len(order) - 0.5, 10.4, "HOP/2 = 10 ms", color=RED, fontsize=7.5, ha="right")
    for i, k in enumerate(order):
        a2.text(i, a[k]["bias_ms"] + 0.3, f"{a[k]['bias_ms']:+.1f}", ha="center", fontsize=8)
    a2.set_xticks(x); a2.set_xticklabels([nice[k] for k in order], fontsize=7.5)
    a2.set_ylabel("signed bias (ms)"); a2.yaxis.grid(True); a2.set_axisbelow(True)
    a2.set_title("The nearest-frame rule is late by exactly half a hop\n"
                 "-- a bug in the readout, not the model", loc="left")
    finish(fig, "f4_subframe_onsets",
           f"Layer {sf_['layer']}, {sf_['n_true']} annotated events, decoder fixed across arms.")


# ------------------------------------------------------------------ F5
def f5():
    """The holdout that matters: ZF -> BirdPark."""
    ah = load("aves_holdout.json")
    if not ah:
        return print("  f5: needs aves_holdout.json")
    z = ah["zf_to_bp"]
    rows = [(k, z[k]["auc"], z[k]["ap"]) for k in z if isinstance(z[k], dict) and "auc" in z[k]]
    rows.sort(key=lambda r: -r[1])
    nm = {"logenergy": "log-energy"}
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    yy = np.arange(len(rows))[::-1]
    cols = [PURPLE if r[0].startswith("aves") else BLUE if r[0].startswith("run11") else MUTE
            for r in rows]
    ax.barh(yy + 0.17, [r[1] for r in rows], height=0.32, color=cols, label="AUC")
    ax.barh(yy - 0.17, [r[2] for r in rows], height=0.32, color=cols, alpha=0.45, label="AP")
    for y, r in zip(yy, rows):
        ax.text(r[1] + 0.006, y + 0.17, f"{r[1]:.3f}", va="center", fontsize=7.5)
        ax.text(r[2] + 0.006, y - 0.17, f"{r[2]:.3f}", va="center", fontsize=7.5, color=MUTE)
    ax.axvline(z["logenergy"]["auc"], color=RED, lw=1, ls=":")
    ax.set_yticks(yy)
    ax.set_yticklabels([nm.get(r[0], r[0].replace("_", " ")) for r in rows])
    ax.set_xlim(0.6, 1.02); ax.xaxis.grid(True); ax.set_axisbelow(True); ax.legend(loc="lower right")
    ax.set_xlabel(f"trained on 30 min ZF, tested on {ah['birdpark']['n_frames_scored']:,} unseen "
                  f"BirdPark frames (prevalence {ah['birdpark']['prevalence']:.3f})")
    ax.set_title("On the only encoder-level holdout, generic animal pretraining beats\n"
                 "colony-specific pretraining at every layer", loc="left")
    finish(fig, "f5_birdpark_holdout",
           "Dotted line is the log-energy baseline. BirdPark is close-miked, so energy is already "
           "strong and differences compress. 118.5 s is ~4 independent 30 s blocks: the bootstrap "
           "here has almost no power, and the signal is the consistency of sign across layers.")


# ------------------------------------------------------------------ F6
def f6():
    """The one improvement that survived a bootstrap."""
    en = load("ensemble_detect.json")
    if not en:
        return print("  f6: needs ensemble_detect.json (run ensemble_detect.py)")
    d = en["in_distribution"]
    order = [k for k in ["run11", "aves", "concat", "stack", "mean"] if k in d]
    nice = {"run11": "run11 alone", "aves": "AVES alone", "concat": "concat 1536-d",
            "stack": "stack on 2 probs", "mean": "mean of 2 probs"}
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.2, 3.1), gridspec_kw=dict(width_ratios=[1.1, 1]))
    x = np.arange(len(order))
    cols = [BLUE, PURPLE] + [MUTE] * (len(order) - 3) + [GREEN]
    a1.bar(x - 0.19, [d[k]["auc"] for k in order], width=0.36, color=cols, label="AUC")
    a1.bar(x + 0.19, [d[k]["ap"] for k in order], width=0.36, color=cols, alpha=0.45, label="AP")
    for i, k in enumerate(order):
        a1.text(i - 0.19, d[k]["auc"] + 0.004, f"{d[k]['auc']:.4f}", ha="center", fontsize=7,
                rotation=90, va="bottom")
        a1.text(i + 0.19, d[k]["ap"] + 0.004, f"{d[k]['ap']:.4f}", ha="center", fontsize=7,
                rotation=90, va="bottom")
    a1.set_xticks(x); a1.set_xticklabels([nice[k] for k in order], fontsize=7.5)
    a1.set_ylim(0.80, 1.02); a1.yaxis.grid(True); a1.set_axisbelow(True); a1.legend(loc="lower left")
    a1.set_title("Averaging two encoders' probabilities beats either,\n"
                 "while concatenating their features does not", loc="left")

    bs = {k: v for k, v in en["bootstrap"].items() if k.startswith("zf_") and k.endswith("_auc")}
    ks = list(bs)[::-1]
    yy = np.arange(len(ks))
    for y, k in enumerate(ks):
        r = bs[k]
        sig = r["verdict"] != "not_distinguishable"
        a2.plot([r["lo"], r["hi"]], [y, y], color=GREEN if sig else MUTE, lw=2.4,
                solid_capstyle="round")
        a2.plot([r["delta"]], [y], "o", color=GREEN if sig else MUTE, ms=5)
    a2.axvline(0, color=INK, lw=0.9)
    a2.set_yticks(yy)
    a2.set_yticklabels([k.replace("zf_", "").replace("_auc", "").replace("_vs_", " − ") for k in ks],
                       fontsize=8)
    a2.set_xlabel("Δ AUC, paired block bootstrap (30 s blocks)")
    a2.xaxis.grid(True); a2.set_axisbelow(True)
    a2.set_title("Green intervals clear zero;\ngrey ones do not", loc="left")
    finish(fig, "f6_ensemble",
           f"Error correlation between the two encoders is {en['error_correlation']:.3f} -- there is "
           "decorrelated error to exploit, and the cheapest combiner exploits it best.")


# ------------------------------------------------------------------ F7
def f7():
    """Sample-exact truth: how much of the measured timing error is the model, and how much the label.

    Everything here is layer 6, because that is the layer the real interpolated onset number was
    measured at -- mixing layers between the synthetic and real arms would compare two things at once.
    The real OFFSET is still grid-quantised (sub-frame interpolation was never applied to offsets on
    real data), so its magnitude cannot drop below the 20 ms grid. That is why the claim rests on the
    signed bias and the duration ratio, which a symmetric quantisation would not produce.
    """
    sc, st = load("synth_timing.json"), load("synth_timing_tails.json")
    gr, sb = load("onset_granular.json"), load("subframe_onset.json")
    if not (sc and gr and sb):
        return print("  f7: needs synth_timing.json, onset_granular.json, subframe_onset.json")
    LAY = f"L{sb['layer']}"
    A = sc["conditions"]["isolated"]["20.0"]["layers"][LAY]
    B = st["conditions"]["isolated"]["20.0"]["layers"][LAY] if st else None
    R = gr[LAY]
    real_on = sb["arms"]["coarse_interp"]["med_abs_err_ms"]      # same decoder as the synthetic arms

    fig, (a1, a2, a3) = plt.subplots(1, 3, figsize=(13.0, 3.5),
                                     gridspec_kw=dict(width_ratios=[1, 1, 1.25], wspace=0.34))

    arms = [("synthetic\nstep edge", A, BLUE)]
    if B:
        arms.append(("synthetic\nquiet tails", B, GREEN))
    arms.append(("real\nhand labels", None, ORANGE))
    x = np.arange(len(arms))

    # --- panel 1: magnitude
    onv = [a[1]["onset_mae_ms"] if a[1] else real_on for a in arms]
    ofv = [a[1]["offset_mae_ms"] if a[1] else R["offset_ms"]["median_abs"] for a in arms]
    a1.bar(x - 0.19, onv, width=0.36, color=[a[2] for a in arms], label="onset")
    a1.bar(x + 0.19, ofv, width=0.36, color=[a[2] for a in arms], alpha=0.45, label="offset")
    for i in range(len(arms)):
        a1.text(i - 0.19, onv[i] + 0.45, f"{onv[i]:.1f}", ha="center", fontsize=7.5)
        a1.text(i + 0.19, ofv[i] + 0.45, f"{ofv[i]:.1f}", ha="center", fontsize=7.5, color=MUTE)
    a1.axhline(20, color=MUTE, lw=0.8, ls=":")
    a1.text(-0.42, 20.7, "20 ms grid", fontsize=7, color=MUTE, ha="left")
    a1.set_xticks(x); a1.set_xticklabels([a[0] for a in arms], fontsize=7.5)
    a1.set_ylabel("median |error| (ms)"); a1.set_ylim(0, 24)
    a1.yaxis.grid(True); a1.set_axisbelow(True); a1.legend(loc="upper left")
    a1.set_title("Exact truth: ~5-7 ms, both edges", loc="left")

    # --- panel 2: bias, where the label shows up
    bv = [a[1]["offset_bias_ms"] if a[1] else R["offset_ms"]["bias"] for a in arms]
    dv = [a[1]["duration_ratio_median"] if a[1] else R["duration_ratio_median"] for a in arms]
    a2.bar(x, bv, width=0.5, color=[a[2] for a in arms])
    a2.axhline(0, color=INK, lw=0.8)
    for i in range(len(arms)):
        a2.text(i, bv[i] + (0.7 if bv[i] >= 0 else -2.0), f"{bv[i]:+.1f}", ha="center", fontsize=8)
        a2.text(i, -5.2, f"dur ×{dv[i]:.2f}", ha="center", fontsize=7.5, color=MUTE)
    a2.set_ylim(-6.8, max(bv) + 4)
    a2.set_xticks(x); a2.set_xticklabels([a[0] for a in arms], fontsize=7.5)
    a2.set_ylabel("signed offset bias (ms)")
    a2.yaxis.grid(True); a2.set_axisbelow(True)
    a2.set_title("Late-offset bias is a label effect", loc="left")

    # --- panel 3: psychometric curve
    iso = sc["conditions"]["isolated"]
    snr = sorted((float(k) for k in iso), reverse=True)
    rec = [iso[f"{v}"]["layers"][LAY]["recall"] for v in snr]
    apv = [iso[f"{v}"]["layers"][LAY]["frame_ap"] for v in snr]
    dur = [iso[f"{v}"]["layers"][LAY]["duration_ratio_median"] for v in snr]
    a3.plot(snr, rec, "-o", color=BLUE, ms=5, label="event recall")
    a3.plot(snr, apv, "-s", color=MUTE, ms=4, label="frame AP")
    if "natural" in sc["conditions"]:
        nv = sc["conditions"]["natural"]["20.0"]["layers"][LAY]["recall"]
        a3.plot([20], [nv], "*", color=RED, ms=15, zorder=5)
        a3.annotate("crowded gaps,\nsame +20 dB", (20, nv), textcoords="offset points",
                    xytext=(26, -6), fontsize=7.5, color=RED, ha="left",
                    arrowprops=dict(arrowstyle="-", color=RED, lw=0.7))
    a3.set_xlabel("call-to-background SNR (dB)"); a3.set_ylabel("recall / AP")
    a3.set_ylim(0, 1.05); a3.set_xlim(23, -13)
    a3.yaxis.grid(True); a3.set_axisbelow(True); a3.legend(loc="lower left")
    a3t = a3.twinx()
    a3t.plot(snr, dur, ":^", color=GREEN, ms=4)
    a3t.axhline(1.0, color=GREEN, lw=0.7, alpha=0.35)
    a3t.set_ylabel("predicted / true duration", color=GREEN)
    a3t.tick_params(axis="y", colors=GREEN); a3t.spines["right"].set_visible(True)
    a3t.spines["right"].set_color(GREEN); a3t.set_ylim(0.4, 1.35)
    a3.set_title("Crowding costs more than 10 dB", loc="left")

    finish(fig, "f7_synthetic_timing",
           f"Layer {sb['layer']} throughout. Real ZF calls (n={sc['config']['n_donors']}) windowed to "
           f"zero outside their own energy support, {sc['config']['taper_ms']:.0f} ms taper, mixed into "
           "call-free background from the held-out 40% of the recording; the probe saw neither. Real "
           "onset is the interpolated arm (same decoder); real offset is grid-quantised because "
           "interpolation was never applied to offsets on real data. 2.1% of false positives fall "
           "within 50 ms of a stitching seam, so the construction is not driving the errors.")



# ------------------------------------------------------------------ F8
def f8():
    """Call-type classification: the task where colony-specific pretraining should win if anywhere."""
    ct = load("aves_calltype.json")
    if not ct:
        return print("  f8: needs aves_calltype.json (run aves_calltype.py)")
    r = ct["run11"]["per_layer_acc"]; a = ct["aves"]["per_layer_acc"]
    x = np.arange(len(r))
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.6, 3.3),
                                 gridspec_kw=dict(width_ratios=[1.35, 1], wspace=0.28))

    a1.plot(x, r, "-o", color=BLUE, ms=4.5, label="run11 (zebra finch colony)")
    a1.plot(x, a, "-s", color=PURPLE, ms=4.5, label="AVES (generic animal)")
    # zoomed: every value sits in a 0.05 band well above the 0.207 majority rate, and the per-layer
    # structure is the point of this panel. The right panel keeps a full-range axis.
    lo = min(min(r), min(a)) - 0.012
    hi = max(max(r), max(a)) + 0.012
    a1.set_ylim(lo, hi)
    a1.text(0.015, 0.04, f"axis zoomed; majority rate is {ct['majority']:.3f}",
            transform=a1.transAxes, fontsize=7, color=RED)
    for nm, v, c in (("run11", r, BLUE), ("AVES", a, PURPLE)):
        b = int(np.argmax(v))
        a1.plot([b], [v[b]], "*", color=c, ms=14, zorder=5)
    a1.set_xticks(x); a1.set_xticklabels([f"L{i}" for i in x], fontsize=7.5)
    a1.set_xlabel("encoder layer"); a1.set_ylabel("accuracy, leave-birds-out")
    a1.yaxis.grid(True); a1.set_axisbelow(True); a1.legend(loc="center right")
    a1.set_title(f"8-way call type, {ct['n_clips']:,} clips, {ct['n_birds']} birds", loc="left")

    rows = [("run11", ct["run11"]["best"]["acc"], BLUE),
            ("AVES", ct["aves"]["best"]["acc"], PURPLE)]
    if "concat" in ct:
        rows.append(("concat", ct["concat"]["acc"], MUTE))
    if "ensemble_mean" in ct:
        rows.append(("mean of both", ct["ensemble_mean"]["acc"], GREEN))
    yy = np.arange(len(rows))[::-1]
    a2.barh(yy, [x_[1] for x_ in rows], color=[x_[2] for x_ in rows], height=0.6)
    for y_, x_ in zip(yy, rows):
        a2.text(x_[1] + 0.004, y_, f"{x_[1]:.4f}", va="center", fontsize=8)
    a2.axvline(ct["majority"], color=RED, lw=1, ls=":")
    a2.set_yticks(yy); a2.set_yticklabels([x_[0] for x_ in rows])
    a2.set_xlim(0.15, max(x_[1] for x_ in rows) + 0.06)
    a2.xaxis.grid(True); a2.set_axisbelow(True)
    a2.set_xlabel("accuracy at each encoder's best layer")
    bs = ct.get("bootstrap_run11_vs_aves", {})
    a2.set_title(f"run11 - AVES {bs.get('delta', 0):+.4f} "
                 f"[{bs.get('lo', 0):+.4f}, {bs.get('hi', 0):+.4f}]", loc="left")

    rep = ct.get("reproduction", {})
    finish(fig, "f8_calltype",
           f"Leave-birds-out, so no bird appears in both train and test. Layers were selected on this "
           f"same metric for both encoders, so both best-layer values are optimistic by the same "
           f"amount. Reproduction of the released per-layer accuracies: max |diff| "
           f"{rep.get('max_abs_diff', float('nan')):.4f}. Bootstrap resamples BIRDS, not clips.")



# ------------------------------------------------------------------ F9
def f9():
    """Reproducing the 2023 AVES number, then removing its defects one at a time."""
    ab = load("aves_2023_ablation.json")
    if not ab:
        return print("  f9: needs aves_2023_ablation.json")
    arms = ab["arms"]
    order = ["1_notebook_full", "2_minus_rectify", "3_minus_padding",
             "4_minus_weak_head", "5_leave_birds_out"]
    nice = {"1_notebook_full": "the 2023 notebook\nas written",
            "2_minus_rectify": "− half-wave\nrectification",
            "3_minus_padding": "− zero padding\n(encode each clip)",
            "4_minus_weak_head": "− 5-epoch SGD head\n(converged probe)",
            "5_leave_birds_out": "− random split\n(leave-birds-out)"}
    order = [k for k in order if k in arms]
    v = [arms[k] for k in order]
    x = np.arange(len(order))
    cols = [RED] + [MUTE] * (len(order) - 2) + [BLUE]

    fig, (a1, a2) = plt.subplots(1, 2, figsize=(11.0, 3.5),
                                 gridspec_kw=dict(width_ratios=[1.7, 1], wspace=0.3))
    a1.bar(x, v, color=cols, width=0.62)
    for i, val in enumerate(v):
        a1.text(i, val + 0.012, f"{val:.3f}", ha="center", fontsize=8.5)
        if i:
            d = v[i] - v[i - 1]
            a1.annotate(f"{d:+.3f}", xy=(i - 0.5, max(v[i], v[i-1]) + 0.075),
                        ha="center", fontsize=7.5,
                        color=GREEN if d > 0.01 else MUTE)
    a1.axhline(ab["majority"], color=MUTE, lw=1, ls=":")
    a1.text(len(order) - 0.45, ab["majority"] + 0.012,
            f"majority {ab['majority']:.3f}", fontsize=7.5, color=MUTE, ha="right")
    a1.set_xticks(x); a1.set_xticklabels([nice[k] for k in order], fontsize=7.5)
    a1.set_ylim(0, max(v) + 0.14)
    a1.set_ylabel(f"11-class accuracy, layer {ab['layer']}")
    a1.yaxis.grid(True); a1.set_axisbelow(True)
    a1.set_title("Same AVES weights throughout — the 2023 number was the pipeline",
                 loc="left")

    mp = ab.get("mean_pairwise_cosine", {})
    if mp:
        keys = [k for k in ("pad_rect", "pad_only", "clip") if k in mp]
        lbl = {"pad_rect": "padded +\nrectified", "pad_only": "padded", "clip": "per-clip"}
        cc = {"pad_rect": RED, "pad_only": ORANGE, "clip": BLUE}
        yy = np.arange(len(keys))[::-1]
        a2.barh(yy, [mp[k] for k in keys], color=[cc[k] for k in keys], height=0.6)
        for y_, k in zip(yy, keys):
            a2.text(mp[k] + 0.012, y_, f"{mp[k]:.3f}", va="center", fontsize=8)
        a2.set_yticks(yy); a2.set_yticklabels([lbl[k] for k in keys], fontsize=8)
        a2.set_xlim(0, 1.05); a2.xaxis.grid(True); a2.set_axisbelow(True)
        a2.set_xlabel("mean pairwise cosine between clip embeddings")
        a2.set_title(f"Padding collapses the space:\na median clip is "
                     f"{100*ab['signal_fraction_median']:.1f}% of the buffer", loc="left")
    finish(fig, "f9_aves_2023_ablation",
           f"{ab['n_clips']} clips, {ab['n_classes']} classes, {ab['n_birds']} birds. The 2022 fairseq "
           "checkpoint and the torchaudio port were verified tensor-identical, so no step here is a "
           "version difference. Padded length 250,606 samples = 15.66 s, taken from the notebook's own "
           "tensor shape.")


# ------------------------------------------------------------------ F10
def f10():
    """Where a colony-specific encoder could still win: per class, low data, and organisation."""
    ca = load("calltype_analysis.json")
    if not ca:
        return print("  f10: needs calltype_analysis.json")
    fig, (a1, a2, a3) = plt.subplots(1, 3, figsize=(13.2, 3.5),
                                     gridspec_kw=dict(width_ratios=[1.25, 1, 1], wspace=0.33))

    pc = ca["per_class"]
    cls = sorted(pc, key=lambda c: pc[c]["diff"])
    d = [pc[c]["diff"] for c in cls]
    cols = [BLUE if x > 0 else PURPLE for x in d]
    yy = np.arange(len(cls))
    a1.barh(yy, d, color=cols, height=0.65)
    a1.axvline(0, color=INK, lw=0.9)
    for y_, c in zip(yy, cls):
        v_ = pc[c]["diff"]
        inside = v_ < -0.15          # long negative bars would collide with the tick labels
        a1.text(v_ + (0.006 if v_ >= 0 else (0.012 if inside else -0.006)), y_,
                f"{v_:+.2f}", va="center", fontsize=7.5,
                color="white" if inside else INK,
                ha="left" if (v_ >= 0 or inside) else "right")
    a1.set_yticks(yy)
    a1.set_yticklabels([f"{c} (n={pc[c]['n']})" for c in cls], fontsize=7.5)
    a1.set_xlabel("run11 − AVES, out-of-fold accuracy")
    a1.xaxis.grid(True); a1.set_axisbelow(True)
    a1.set_title("Per call type: blue = run11 ahead", loc="left")

    de = ca["data_efficiency"]
    ks = sorted(int(k) for k in set(de["run11"]) & set(de["aves"]))
    for nm, c, mk in (("run11", BLUE, "o"), ("aves", PURPLE, "s")):
        m = np.array([de[nm][str(k)]["mean"] for k in ks])
        sd = np.array([de[nm][str(k)]["sd"] for k in ks])
        a2.plot(ks, m, "-" + mk, color=c, ms=4.5,
                label="run11 (colony)" if nm == "run11" else "AVES (generic)")
        a2.fill_between(ks, m - sd, m + sd, color=c, alpha=0.15, lw=0)
    a2.set_xlabel("number of training birds"); a2.set_ylabel("accuracy on held-out birds")
    a2.yaxis.grid(True); a2.set_axisbelow(True); a2.legend(loc="lower right")
    a2.set_title("Low-data regime", loc="left")

    un = ca["unsupervised"]
    ks2 = sorted(int(k) for k in un["run11"])
    w = 0.36
    xx = np.arange(len(ks2))
    a3.bar(xx - w/2, [un["run11"][str(k)]["ami_calltype"] for k in ks2], width=w,
           color=BLUE, label="run11")
    a3.bar(xx + w/2, [un["aves"][str(k)]["ami_calltype"] for k in ks2], width=w,
           color=PURPLE, label="AVES")
    a3.plot(xx - w/2, [un["run11"][str(k)]["ami_bird"] for k in ks2], "v", color=INK, ms=5,
            label="AMI vs bird identity")
    a3.plot(xx + w/2, [un["aves"][str(k)]["ami_bird"] for k in ks2], "v", color=INK, ms=5)
    a3.set_xticks(xx); a3.set_xticklabels([f"k={k}" for k in ks2], fontsize=8)
    a3.set_ylabel("AMI"); a3.yaxis.grid(True); a3.set_axisbelow(True)
    a3.legend(loc="upper center", fontsize=7, ncol=3, bbox_to_anchor=(0.5, 1.02),
              columnspacing=1.0, handletextpad=0.5)
    a3.set_ylim(0, max(un["aves"][str(k)]["ami_calltype"] for k in ks2) * 1.42)
    a3.set_title("Unsupervised: does the space organise\nby call type, or by who is calling?",
                 loc="left")
    finish(fig, "f10_where_run11_could_win",
           f"{ca['n_clips']} clips, {len(ca['classes'])} classes, {ca['n_birds']} birds, layer "
           f"{ca['layers']['run11']} both. Overall out-of-fold: run11 {ca['overall']['run11']:.4f}, "
           f"AVES {ca['overall']['aves']:.4f}. Triangles mark AMI against bird identity — the confound "
           "a call-type clustering must NOT be tracking.")


# ------------------------------------------------------------------ F11
def f11():
    """UMAP of both spaces, coloured by call type."""
    import numpy as _np
    p = Path.home() / "zf_labelset/zf_detection_dataset_v1/features/ct11_umap.npz"
    if not p.exists():
        return print("  f11: needs ct11_umap.npz (run calltype_analysis.py)")
    z = _np.load(p, allow_pickle=True)
    classes = [str(c) for c in z["classes"]]
    y = z["y"]
    cmap = plt.get_cmap("tab20")
    fig, axes = plt.subplots(1, 2, figsize=(11.4, 5.0))
    for ax, nm, ttl in zip(axes, ("run11", "aves"),
                           ("run11 (zebra finch colony)", "AVES (generic animal)")):
        E = z[nm]
        for i, c in enumerate(classes):
            m = y == i
            ax.scatter(E[m, 0], E[m, 1], s=4, color=cmap(i % 20), label=c, alpha=0.65,
                       linewidths=0)
        ax.set_title(ttl, loc="left")
        ax.set_xticks([]); ax.set_yticks([])
        for sp in ax.spines.values():
            sp.set_visible(False)
    axes[1].legend(markerscale=3, fontsize=7.5, loc="center left", bbox_to_anchor=(1.01, 0.5),
                   ncol=1)
    finish(fig, "f11_umap_calltype",
           "Same UMAP settings for both (n_neighbors 25, min_dist 0.15, seed 0) on standardised "
           "layer-3 embeddings. UMAP geometry is not a metric — read it alongside the clustering AMI "
           "in f10, which is chance-corrected.")


FIGS = {"f1": f1, "f2": f2, "f3": f3, "f4": f4, "f5": f5, "f6": f6, "f7": f7,
        "f8": f8, "f9": f9, "f10": f10, "f11": f11}

if __name__ == "__main__":
    want = sys.argv[1:] or list(FIGS)
    for k in want:
        if k not in FIGS:
            print(f"  unknown figure {k}; have {list(FIGS)}")
            continue
        print(f"{k}:")
        FIGS[k]()
